### ISSUE TITLE
delayed update of spatial profiles after animation has stopped

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#543]
Spatial profiles keep updating after animation has stopped.

![Jun-23-2020 18-13-27](https://user-images.githubusercontent.com/20819712/85391880-56cc7200-b57d-11ea-96c2-827eeff47882.gif)

This issue is easier to be re-produced under poor network condition.

**Comment by veggiesaurus** [comment]
The underlying issue here is that the flow control messages are sent to the backend, but not handled correctly. As such, the backend simply sends new frames as fast as it can, rather than at a rate that the frontend can handle. When the animation is stopped, a large number of frames are still being received by the frontend, so all incoming traffic is blocked until these frames are received and discarded.

**Comment by kswang1029** [comment]
At 1 fps, I see spatial profile updates slightly faster than the image.

**Comment by veggiesaurus** [comment]
> At 1 fps, I see spatial profile updates slightly faster than the image.

are the spatial profiles just delivered first?

**Comment by kswang1029** [comment]
YES we see the following sequence:
<== SPATIAL_PROFILE_DATA [Stream]
<== REGION_HISTOGRAM_DATA [Stream]
<== RASTER_TILE_SYNC [Stream]
<== RASTER_TILE_DATA [Stream]
....

<img width="424" alt="Screen Shot 2020-06-23 at 6 42 22 PM" src="https://user-images.githubusercontent.com/20819712/85394651-71a0e580-b581-11ea-8094-3378cc9c543c.png">
...
<img width="424" alt="Screen Shot 2020-06-23 at 6 43 10 PM" src="https://user-images.githubusercontent.com/20819712/85394677-79f92080-b581-11ea-9c89-55f6a309c9b0.png">

**Comment by veggiesaurus** [comment]
> YES we see the following sequence:
> <== SPATIAL_PROFILE_DATA [Stream]
> <== REGION_HISTOGRAM_DATA [Stream]
> <== RASTER_TILE_SYNC [Stream]
> <== RASTER_TILE_DATA [Stream]
> ....

But they're still all delivered at 1 fps, right? So it's just a matter of how they are ordered

**Comment by Kechil** [comment]
Same as #366

**Comment by veggiesaurus** [comment]
@robsimmonds to fix flow control issue, which should solve this issue as well as #366

**Comment by kswang1029** [comment]
@robsimmonds @veggiesaurus this issue is much improved in 
origin/rwjs/update_ani_perams 045bd2e 5034 2020-07-28 16:24:19 UTC

We still see few spatial profile updates after pressing the stop button of the animator, but I think the usability is much improved.
